version: '3'

services:
  server:
    image: loadbalancer/server
    ports:
      - "2222"
      - "7777:7777"
  
  worker:
    depends_on:
      - server
    image: loadbalancer/worker
    expose:
      - "5555"
    links:
      - server